server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.hellodev.api.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 1234
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    # 客户端注册进eureka服务列表内
    service-url:
       # defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    # 自定义服务名称信息
    instance-id: microservicecloud-dept8001
    # 访问路径可以显示IP地址
    prefer-ip-address: true

# 微服务信息描述
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}