server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_recruit?characterEncoding=UTF-8
    username: root
    password: 1234
  jpa: 
    database: MySQL
    show-sql: true
