server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          #GitHub上面的git仓库名字
          uri: git@github.com:lujiahao0708/microservicecloud-config.git

