server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true