server:
  port: 6868 #服务端口

eureka:
  instance:
    # eureka服务端的实例名称
    hostname: eureka
  client:
    # #false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://127.0.0.1:${server.port}/eureka/
