server:
  port: 80


eureka:
  client:
    register-with-eureka: false #客户端不注册进eureka服务列表内
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
